name = "production-app-pages"
compatibility_date = "2024-05-01"
pages_build_output_dir = "."

[observability]
enabled = true

# Local-only Wrangler config example.
# Do NOT commit a file named "wrangler.toml" if you want to manage
# bindings from the Cloudflare Pages dashboard.
#
# To use locally, copy this file to wrangler.toml and (optionally)
# add a D1 binding with your database_id:
#
# [[d1_databases]]
# binding = "DB"
# database_name = "production_qi"
# database_id = "<your D1 UUID>"
