name = "production-app-pages"
compatibility_date = "2024-05-01"
pages_build_output_dir = "."

[observability]
enabled = true

# Note: Do NOT configure D1 here for Pages CI.
# Add the D1 binding in the Cloudflare Pages dashboard instead:
# Pages → Project → Settings → Functions → D1 Bindings → Add (binding name: DB)
